PORTNAME=		dsc-collector
PORTVERSION=	201502251630
CATEGORIES=		dns ipv6
MASTER_SITES=   GH

MAINTAINER=		john.bond@icann.org
COMMENT=		DNS Data collection

LICENSE=		BSD3CLAUSE


.include <bsd.port.mk>
